### ISSUE TITLE
go-ide.md: Atom開発元について

### ISSUE THREAD

**Issue by zchee** [unirita/go-website#1]
日本語で失礼します。

Goをはじめて日が浅いので、当チュートリアル読ませていただいております。
記載ミスを発見したのでissueポストさせてください。

https://github.com/unirita/go-website/blob/master/content/post/go-ide.md#go%E3%81%AE%E9%96%8B%E7%99%BA%E7%92%B0%E5%A2%83
にありますAtom Editorの開発元、GoogleではなくGitHubではないでしょうか？
https://github.com/atom/atom/blob/master/LICENSE.md

読者に対してより、ライセンスに関わりそうな点でしたので、些細ですがご報告させていただきました。
修正するとなると前後の文章とのつながりを考えなければいけなそうでしたので、PRではなくissueにて。

**Comment by ghost** [comment]
@zchee さん
issueの投稿、ありがとうございます。
完全に記載ミスでしたので、修正させていただきました。

今後もGo言語に関するノウハウを増やして行こうと考えておりますので、
引き続きご活用していただけると幸いです。
